
// Generated by UpdateVersionInfo 1.0.15
//# 2.0.0.1
//# 11.09.2020

using System;

namespace ZPF
{
   public static class VersionInfo
   {
      public static string sVersion { get => "1.4.4.17"; }
      public static Version Version { get => new Version(sVersion); }

      public static string BuildOn { get => DateTime.Now.ToString("11.09.2020"); }
      public static int RevisionNumber { get => Version.Revision; }
   }
}
